---
- name: Install web server
  hosts: intranet
  become: true
  tasks: 

    - name: Ensure latest package httpd and firewalld
      ansible.builtin.yum:
        name:
          - httpd
          - firewalld
        state: latest

    - name: Ensure enabled and running service firewalld
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: yes

    - name: permit traffic in default zone for http service
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true

    - name: Start service httpd, if not started
      ansible.builtin.service:
        name: httpd
        state: started

    - name: Copy using inline content
      ansible.builtin.copy:
        content: "Welcome to the example.com intranet! \n (Bienvenido a la intranet de example.com). \n"
        dest: /var/www/html/index.html
      

- name: TEST web server
  hosts: localhost
  tasks:
  
    - name: Ensure response code return 200 is ok
      ansible.builtin.uri:
        url: http://vm-20-node2-ansible.example.com
        method: GET
        return_content: true
        status_code: 200
